#  CRMO Web NodeJS build
image: node:12.20

definitions: 
  caches:
    submodule: ellaisys-lib

  steps:
    - step: &load-submodules
        name: Load GIT Submodules
        caches:
          - submodule
        script:
          - cd $BITBUCKET_CLONE_DIR
          - echo $BITBUCKET_CLONE_DIR
          - git submodule update --init --recursive

    - step: &install-angular
        name: Install Anugular & Project Dependencies
        caches:
          - node
        script:
          - cd $BITBUCKET_CLONE_DIR
          - echo $BITBUCKET_CLONE_DIR
          - npm install -g @angular/cli@11.1.4
          - node -v
          - npm -v
          - echo "Angular Installed"

    - step: &code-linting
        name: Code linting
        script:
          - npm install eslint

    - step: &deploy
        name: Deploy to AWS S3
        image: atlassian/pipelines-awscli
        script:
          - cd dist/
          - aws s3 sync --delete . s3://$AWS_S3_BUCKET/$AWS_S3_TARGET_FOLDER/dev
          - echo "Uploaded to AWS S3 WEB"

pipelines:          
  branches:
    master:
      - parallel:
        - step:
            name: Build and Test
            script:
              - echo "Starting CRM Omni PROD Build"
              - echo "HTACCESS Copied"
            artifacts:
              - # dist/**
        - step:
            name: Code linting
            script:
              - # npm install eslint
              - # npx eslint 
    
    phase1.0:
      # - step: 
      #     <<: *load-submodules

      - step:
          <<: *install-angular

      - step:
          name: Build and Test
          script:
            #- cd $BITBUCKET_CLONE_DIR
            - git submodule update --init --recursive
            - echo "Loaded GIT Submodules"
            - npm install
            - echo "Project Dependencies installed"
            - echo "--- Starting CRM Omni Dev Build ---"
            - npm run build -prod ellaisys-lib
            - echo "EllaiSys Library Build Complete"
            - npm run build -prod crmo-lib
            - echo "CRMO Library Build Complete"
            - npm run build -prod --base-href=/$NG_BACKEND_BASE_HREF/ crmo-backend
            - echo "Ng App Build Complete"
            - cp .htaccess.dev dist/.htaccess
            - echo "HTACCESS Copied"
            - cp dist/index.html dist/index.php
            - echo "HTML renamed as PHP"
          artifacts:
            - dist/**

      - step: *code-linting

      - step: *deploy