#  CRMO Web NodeJS build

image: node:10.15.3

pipelines:
  default:
    - step:
        name: Starting Build
        caches:
          - node
        script:
          - echo "Creating Angular Build environment"
          
    - step:
        name: Create Environment
        deployment: production
        script:
          - cd /
          - npm install -g @angular/cli@10.2.0
          - npm install
          
  branches:
    master:
      - parallel:
        - step:
            name: Build and Test
            script:
              - echo "Starting CRM Omni PROD Build"
              - npm run build:crmo-build-all
              - echo "Ng Build Complete"
              - cp .htaccess.prod dist/.htaccess
              - echo "HTACCESS Copied"
        - step:
            name: Code linting
            script:
              - npm install eslint
              - npx eslint .
            caches:
              - node  
    
    phase1.0:
      - parallel:
        - step:
            name: Build and Test
            script:
              - echo "Starting CRM Omni Dev Build"
              - npm run build:crmo-build-all-dev
              - echo "Ng Build Complete"
              - cp .htaccess dist
              - echo "HTACCESS Copied"
        - step:
            name: Code linting
            script:
              - npm install eslint
              - npx eslint .
            caches:
              - node


