#  CRMO Web NodeJS build

image: node:10.15.3

clone:
  lfs: true

pipelines:
  default:
    - step:
        name: Versions
        script:
          - node -v
          - npm -v

    - step:
        name: Install Node
        script:
          - echo "Installed node:6.14.5"

    - step:
        name: Install Anugular
        script:
          - cd /
          - npm install -g @angular/cli@11.0.7
          - echo "Creating Angular Build environment"
          
  branches:
    master:
      - parallel:
        - step:
            name: Build and Test
            script:
              - echo "Starting CRM Omni PROD Build"
              - npm run build:crmo-build-all
              - echo "Ng Build Complete"
              - cp .htaccess dist
              - echo "HTACCESS Copied"
            artifacts:
              - dist/**
        - step:
            name: Code linting
            script:
              - npm install eslint
              - npx eslint .
            caches:
              - node  
    
    phase1.0.dev:
      - step:
          name: Build and Test
          deployment: test
          script:
            - node -v
            - npm -v
            - git submodule update --init --recursive
            - npm install -g @angular/cli@11.0.7
            - npm install
            - echo "Starting CRM Omni Dev Build"
            - npm run ng build -prod ellaisys-lib
            - echo "EllaiSys Library Build Complete"
            - npm run ng build -prod crmo-lib
            - echo "CRMO Library Build Complete"
            - npm run ng build -prod --base-href=/$NG_BACKEND_BASE_HREF/ crmo-backend
            - echo "Ng Build Complete"
            - cp .htaccess.dev dist/.htaccess
            - echo "HTACCESS Copied"
          artifacts:
            - node_modules/**
            #- dist/**

      - step:
          name: Code linting
          script:
            - npm install eslint
            - npx eslint .
          caches:
            - node

      - step:
          name: Deploy to S3 Web
          image: atlassian/pipelines-awscli
          script:
            - cd dist/
            - aws s3 sync --delete . s3://$AWS_S3_BUCKET/$AWS_S3_TARGET_FOLDER/dev
            - echo "Uploaded to AWS S3 WEB"


